# Generated by Django 2.2.1 on 2019-05-22 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
                ('starting_salary', models.PositiveIntegerField()),
                ('job_description', models.TextField()),
                ('address', models.CharField(max_length=50)),
                ('employer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.EmployerUser')),
            ],
        ),
    ]
