# Generated by Django 2.2.1 on 2019-05-22 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_joboffer'),
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('applicant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.ApplicantUser')),
                ('job_offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emp.JobOffer')),
            ],
        ),
    ]
